    server {
#         listen 443 default_server ssl;
#         listen [::]:443 ssl;
        listen 80;
        listen [::]:80;
        server_name metaksander.nomorepartiessbs.ru;

#         ssl_certificate /etc/letsencrypt/live/metaksander.nomorepartiessbs.ru/fullchain.pem;
#         ssl_certificate_key /etc/letsencrypt/live/metaksander.nomorepartiessbs.ru/privkey.pem;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/ {
            proxy_pass http://backend:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /content/ {
            proxy_pass http://backend:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        types {
            text/html html htm shtml;
            text/css css;
            text/xml xml;
            image/gif gif;
            image/jpeg jpeg jpg;
            application/javascript js;
            text/plain txt;
            image/png png;
            image/svg+xml svg svgz;
            image/webp webp;
            application/java-archive jar war ear;
            application/msword doc;
            application/pdf pdf;
            application/vnd.ms-excel xls;
            application/x-7z-compressed 7z;
            application/x-rar-compressed rar;
            application/x-x509-ca-cert der pem crt;
            application/zip zip;
            audio/mpeg mp3;
            audio/x-m4a m4a;
            video/mp4 mp4;
            video/quicktime mov;
        }
    }

#     server {
#         listen 80;
#         listen [::]:80;
#         server_name metaksander.nomorepartiessbs.ru;
#
#         location /.well-known/acme-challenge/ {
#             root /var/www/certbot;
#         }
#
#         location / {
#             return 301 https://$host$request_uri;
#         }
#     }
